#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Motor,  port10,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port1,           leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void FWDBCKEN()
{
	wait1Msec(2000);  // 2 Second Delay

	//Clear Encoders
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] < 1440)  //4ft forward
	{
		motor[rightMotor] = 115;
		motor[leftMotor] = 127;
	}
	SensorValue[rightEncoder] = 0; //reset encoders
	SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] < 625) //turn around 180 degrees
	{
		motor[rightMotor] = 127;
		motor[leftMotor] = -127;
	}
	SensorValue[rightEncoder] = 0; //reset encoders
	SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] < 1440) //4ft forward (back towards start)
	{
		motor[rightMotor] = 115;
		motor[leftMotor] = 127;
	}
	motor[leftMotor] = -1; //reverse motors for abrupt stop (1 second)
	motor[rightMotor] = -1;
	wait1Msec(1000);
}
task main()
{
	FWDBCKEN();
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
