#pragma config(Motor,  port10,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port1,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at full power for 3 seconds
	motor[rightMotor] = -127;
	motor[leftMotor]  = -127;
	wait1Msec(740.416);	//go forward 20"
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
	motor[rightMotor] = -127;
	motor[leftMotor] = 1;
	wait1Msec(900); //turn left 90 degrees
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
	motor[leftMotor] = -127;
	motor[rightMotor] = -127;
	wait1Msec(518.29); // go forward 14"
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
	motor[leftMotor] = -127;
	motor[rightMotor] = 1;
	wait1Msec(900); //turn right 90 degrees
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
	motor[leftMotor] = -127;
	motor[rightMotor] = -127;
	wait1Msec(333.18); //go forward 9"
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
	motor[leftMotor] = -127;
	motor[rightMotor] = 1;
	wait1Msec(900); //turn right 90 degrees
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
	motor[leftMotor] = -127;
	motor[rightMotor] = -127;
	wait1Msec(259.14); //go forward 7"
	motor[rightMotor] = 1;
	motor[leftMotor] = 1;
	wait1Msec(1000); //pause between instructions
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
