#pragma config(Sensor, in3,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in4,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  rightEncoderBottom, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoderTop, sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  LimitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl8,  Sonar,          sensorSONAR_raw)
#pragma config(Sensor, dgtl11, Button,         sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                - Clawbot Single Joystick Control -                                 *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left to drive the robot. Use notes below     *|
|*  to reconfigure which joystick is used. The joystick buttons are used to raise and lower the arm.	*|
|*  The joystick buttons are used to open and close the claw.																					*|
|*																																																		*|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)	Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)	Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*		3)	Button 5U and 5L are on the front left side of the joystick.																*|
|*		3)	Button 6U and 6L are on the front right side of the joystick.																*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]        [Name]          [Type]                               [Description]            *|
|*    Motor - Port 2   rightMotor    VEX 393 Motor                         Right drive motor          *|
|*    Motor - Port 6   clawMotor     VEX 393 Motor w/ Motor Controler 29   Claw motor                 *|
|*    Motor - Port 7   armMotor      VEX 393 Motor w/ Motor Controler 29   Arm motor                  *|
|*    Motor - Port 10  leftMotor     VEX 393 Motor                         Left drive motor           *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
bool Stop = false;
void ResetEncoder()
{
	SensorValue[rightEncoderBottom] = 0;
	SensorValue[leftEncoderTop] = 0;
}
void Rotate90()
{
	ResetEncoder();
	while (SensorValue[rightEncoderBottom] < 342.1605)
	{
		motor[rightMotor] = 63;
		motor[leftMotor] = -63;
		if (vexRT[Btn8D] == 1)
		{
			Stop = true;
		}
	}
}
void Square()
{
	for (int x = 0; x < 4; x++)
	{
		ResetEncoder();
		while (SensorValue[rightEncoderBottom] < 1100.63)
		{
			motor[rightMotor] = 127;
			motor[leftMotor] = 127;
		}
		ResetEncoder();
		while(SensorValue[rightEncoderBottom] < 342.16)
		{
			motor[rightMotor] = 127;
			motor[leftMotor] = -127;
		}
		ResetEncoder();
	}
}
void Maze()
{
	ResetEncoder();
	while (Stop == false)
	{
		if (SensorValue[Sonar] == 400)
		{
			motor[rightMotor] = 63;
			motor[leftMotor] = 63;
		}
		if (SensorValue[Sonar] > 400)
		{
			motor[leftMotor] = 63;
			motor[rightMotor] = 10;
		}
		if (SensorValue[Sonar] < 400)
		{
			motor[leftMotor] = 10;
			motor[rightMotor] = 63;
		}
		if (SensorValue[Button] == 1)
		{
			ResetEncoder();
			while (SensorValue[rightEncoderBottom] > -300)
			{
				motor[rightMotor] = -63;
				motor[leftMotor] = -63;
			}
			motor[rightMotor] = 1;
			motor[leftMotor] = 1;
			wait1Msec(500);
			ResetEncoder();
			Rotate90();
		}
		if (SensorValue[LimitSwitch] == 1)
		{
			ResetEncoder();
			while (SensorValue[rightEncoderBottom] > -300)
			{
				motor[rightMotor] = -63;
				motor[leftMotor] = -63;
			}
			ResetEncoder();
			while (SensorValue[leftEncoderTop] < (342.1605))
			{
				motor[rightMotor] = -63;
				motor[leftMotor] = 63;
			}
		}
		if (vexRT[Btn8D] == 1)
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			wait1Msec(500);
			Stop = true;
		}
	}
}
task main ()
{
	while(true)
	{
		//Driving Motor Control
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
		//Arm Control
		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -127;
		}
		else
		{
			motor[armMotor] = 0;
		}
		if (SensorValue[LightSensor] > 600)
		{
			Square();
		}
		if (vexRT[Btn8U] == 1)
		{
			Stop = false;
			Maze();
		}
		if (vexRT[Btn7U] == 1)
		{
			Rotate90();
		}
	}
}
