#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward for 5 rotations of the left shaft encoder.       *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void Clear()
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

}
void Forward(float x) //float x being the number of desired inches
{
	Clear();
	while(SensorValue[rightEncoder] < (x/6.28)*360) //desired inches converted into degrees of wheel rotation
	{
		motor[rightMotor] = 127;
		motor[leftMotor] = 127;
	}
}
void Backward(float x) //float x being the number of desired inches
{
	Clear();
	while(SensorValue[rightEncoder] < (-x/6.28)*360) //desired inches converted to degrees and making them negative because backwards
	{
		motor[rightMotor] = -127;
		motor[leftMotor] = -127;
	}
}
void TurnLeft(float x) //float x being the desired degrees to turn assuming the wheels are 4 inches apart with a 2 inch diameter
{
	Clear();
	while(SensorValue[rightEncoder] < (x/6.28)*360) // convert degrees into degrees on each wheel needed
	{
		motor[rightMotor] = 127;
		motor[leftMotor] = 0;
	}
}
//void TurnRight(float x) //float x being the desired degrees to turn assuming the wheels are 4 inches apart with a 2 inch diameter
//{
//Clear();
//while(SensorValue[leftEncoder] < (x/6.28)*360) // convert degrees into degrees on each wheel needed
//{
//motor[rightMotor] = 0;
//motor[leftMotor] = 127;
//}
//}

task main()
{
	wait1Msec(2000);  // 2 Second Delay
	Clear();
	Forward(24);
	TurnLeft(45);
	Backward(60);
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
